" Kokedera Rain - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-rain'

highlight Normal guifg=#b8d8c8 guibg=#111a19 guisp=NONE gui=NONE ctermfg=152 ctermbg=233 cterm=NONE
highlight NormalNC guifg=#b8d8c8 guibg=#111a19 guisp=NONE gui=NONE ctermfg=152 ctermbg=233 cterm=NONE
highlight NormalFloat guifg=#b8d8c8 guibg=#141e1d guisp=NONE gui=NONE ctermfg=152 ctermbg=234 cterm=NONE
highlight Pmenu guifg=#b8d8c8 guibg=#141e1d guisp=NONE gui=NONE ctermfg=152 ctermbg=234 cterm=NONE
highlight FloatBorder guifg=#354a45 guibg=#141e1d guisp=NONE gui=NONE ctermfg=238 ctermbg=234 cterm=NONE
highlight WinSeparator guifg=#354a45 guibg=#141e1d guisp=NONE gui=NONE ctermfg=238 ctermbg=234 cterm=NONE
highlight VertSplit guifg=#354a45 guibg=#141e1d guisp=NONE gui=NONE ctermfg=238 ctermbg=234 cterm=NONE
highlight FloatTitle guifg=#6cc4b2 guibg=NONE guisp=NONE gui=bold ctermfg=79 ctermbg=NONE cterm=bold
highlight Title guifg=#6cc4b2 guibg=NONE guisp=NONE gui=bold ctermfg=79 ctermbg=NONE cterm=bold
highlight Cursor guifg=#111a19 guibg=#5ae6e6 guisp=NONE gui=NONE ctermfg=233 ctermbg=80 cterm=NONE
highlight lCursor guifg=#111a19 guibg=#5ae6e6 guisp=NONE gui=NONE ctermfg=233 ctermbg=80 cterm=NONE
highlight CursorLine guifg=NONE guibg=#192625 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#192625 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#192625 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight Visual guifg=#b8d8c8 guibg=#263d39 guisp=NONE gui=NONE ctermfg=152 ctermbg=236 cterm=NONE
highlight VisualNOS guifg=#b8d8c8 guibg=#263d39 guisp=NONE gui=NONE ctermfg=152 ctermbg=236 cterm=NONE
highlight Search guifg=#b8d8c8 guibg=#304544 guisp=NONE gui=NONE ctermfg=152 ctermbg=237 cterm=NONE
highlight IncSearch guifg=#111a19 guibg=#d4c88e guisp=NONE gui=bold ctermfg=233 ctermbg=186 cterm=bold
highlight CurSearch guifg=#111a19 guibg=#d4c88e guisp=NONE gui=bold ctermfg=233 ctermbg=186 cterm=bold
highlight Substitute guifg=#111a19 guibg=#c45a5a guisp=NONE gui=NONE ctermfg=233 ctermbg=167 cterm=NONE
highlight MatchParen guifg=#d4c88e guibg=#304544 guisp=NONE gui=bold ctermfg=186 ctermbg=237 cterm=bold
highlight LineNr guifg=#5e8a7b guibg=#111a19 guisp=NONE gui=NONE ctermfg=66 ctermbg=233 cterm=NONE
highlight LineNrAbove guifg=#5e8a7b guibg=#111a19 guisp=NONE gui=NONE ctermfg=66 ctermbg=233 cterm=NONE
highlight LineNrBelow guifg=#5e8a7b guibg=#111a19 guisp=NONE gui=NONE ctermfg=66 ctermbg=233 cterm=NONE
highlight CursorLineNr guifg=#6cc4b2 guibg=#192625 guisp=NONE gui=bold ctermfg=79 ctermbg=235 cterm=bold
highlight SignColumn guifg=#87aa9d guibg=#111a19 guisp=NONE gui=NONE ctermfg=109 ctermbg=233 cterm=NONE
highlight FoldColumn guifg=#87aa9d guibg=#111a19 guisp=NONE gui=NONE ctermfg=109 ctermbg=233 cterm=NONE
highlight Folded guifg=#87aa9d guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight NonText guifg=#354a45 guibg=NONE guisp=NONE gui=NONE ctermfg=238 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#354a45 guibg=NONE guisp=NONE gui=NONE ctermfg=238 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#354a45 guibg=NONE guisp=NONE gui=NONE ctermfg=238 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#354a45 guibg=NONE guisp=NONE gui=NONE ctermfg=238 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#87aa9d guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#b8d8c8 guibg=#304544 guisp=NONE gui=bold ctermfg=152 ctermbg=237 cterm=bold
highlight TabLineSel guifg=#b8d8c8 guibg=#304544 guisp=NONE gui=bold ctermfg=152 ctermbg=237 cterm=bold
highlight StatusLineNC guifg=#87aa9d guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight TabLine guifg=#87aa9d guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight TabLineFill guifg=#87aa9d guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight WinBarNC guifg=#87aa9d guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight WinBar guifg=#b8d8c8 guibg=#192625 guisp=NONE gui=NONE ctermfg=152 ctermbg=235 cterm=NONE
highlight PmenuSel guifg=#b8d8c8 guibg=#304544 guisp=NONE gui=bold ctermfg=152 ctermbg=237 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#192625 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#354a45 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
highlight PmenuMatch guifg=#6cc4b2 guibg=NONE guisp=NONE gui=bold ctermfg=79 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#6cc4b2 guibg=#304544 guisp=NONE gui=bold ctermfg=79 ctermbg=237 cterm=bold
highlight WildMenu guifg=#111a19 guibg=#6cc4b2 guisp=NONE gui=NONE ctermfg=233 ctermbg=79 cterm=NONE
highlight Directory guifg=#6fbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Question guifg=#6cc4b2 guibg=NONE guisp=NONE gui=NONE ctermfg=79 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#6cc4b2 guibg=NONE guisp=NONE gui=NONE ctermfg=79 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#6cc4b2 guibg=NONE guisp=NONE gui=NONE ctermfg=79 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Error guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Comment guifg=#506b61 guibg=NONE guisp=NONE gui=italic ctermfg=59 ctermbg=NONE cterm=italic
highlight Constant guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight String guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Character guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Number guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Float guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight Function guifg=#6fbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Statement guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Label guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Exception guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Operator guifg=#709086 guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#709086 guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Include guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Define guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Macro guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#4ca6a6 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight Type guifg=#3d84ad guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#3d84ad guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight Structure guifg=#3d84ad guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#3d84ad guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight Special guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight Tag guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight Debug guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#506b61 guibg=NONE guisp=NONE gui=bold ctermfg=59 ctermbg=NONE cterm=bold
highlight Underlined guifg=#5a8b9e guibg=NONE guisp=NONE gui=underline ctermfg=67 ctermbg=NONE cterm=underline
highlight Ignore guifg=#5e8a7b guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE
highlight Todo guifg=#d4c88e guibg=#192625 guisp=NONE gui=bold ctermfg=186 ctermbg=235 cterm=bold
highlight DiffAdd guifg=#6fbf9f guibg=#192625 guisp=NONE gui=NONE ctermfg=73 ctermbg=235 cterm=NONE
highlight DiffChange guifg=#c49a5c guibg=#192625 guisp=NONE gui=NONE ctermfg=173 ctermbg=235 cterm=NONE
highlight DiffDelete guifg=#c45a5a guibg=#192625 guisp=NONE gui=NONE ctermfg=167 ctermbg=235 cterm=NONE
highlight DiffText guifg=#b8d8c8 guibg=#304544 guisp=NONE gui=bold ctermfg=152 ctermbg=237 cterm=bold
highlight diffAdded guifg=#6fbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#c45a5a guibg=#192625 guisp=NONE gui=NONE ctermfg=167 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#c49a5c guibg=#192625 guisp=NONE gui=NONE ctermfg=173 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#c49a5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#5a8b9e guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#5a8b9e guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#5a8b9e guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#5a8b9e guibg=#192625 guisp=NONE gui=NONE ctermfg=67 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#5a8b9e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#8cbea7 guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#8cbea7 guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#8cbea7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#6fbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#6fbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#6fbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#6fbf9f guibg=#192625 guisp=NONE gui=NONE ctermfg=73 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#6fbf9f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#506b61 guibg=NONE guisp=NONE gui=italic ctermfg=59 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#c49a5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#5a8b9e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#9a7abf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#304544 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#304544 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#304544 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspInlayHint guifg=#87aa9d guibg=#192625 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
highlight LspCodeLens guifg=#87aa9d guibg=NONE guisp=NONE gui=italic ctermfg=109 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#8cbea7 guibg=NONE guisp=NONE gui=bold,underline ctermfg=109 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#192625', '#c45a5a', '#5ab8b8', '#bfa243', '#3d84ad', '#9a7abf', '#5a8b9e', '#b8d8c8', '#445a54', '#d47070', '#6cc4b2', '#d4c88e', '#4a9ec2', '#b49ad4', '#7aa6c2', '#cae8d8']
