" Kokedera Summer - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-summer'

highlight Normal guifg=#d2e7bd guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
highlight NormalNC guifg=#d2e7bd guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
highlight NormalFloat guifg=#d2e7bd guibg=#0e1d0d guisp=NONE gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
highlight Pmenu guifg=#d2e7bd guibg=#0e1d0d guisp=NONE gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
highlight FloatBorder guifg=#2c4725 guibg=#0e1d0d guisp=NONE gui=NONE ctermfg=236 ctermbg=233 cterm=NONE
highlight WinSeparator guifg=#2c4725 guibg=#0e1d0d guisp=NONE gui=NONE ctermfg=236 ctermbg=233 cterm=NONE
highlight VertSplit guifg=#2c4725 guibg=#0e1d0d guisp=NONE gui=NONE ctermfg=236 ctermbg=233 cterm=NONE
highlight FloatTitle guifg=#56d165 guibg=NONE guisp=NONE gui=bold ctermfg=77 ctermbg=NONE cterm=bold
highlight Title guifg=#56d165 guibg=NONE guisp=NONE gui=bold ctermfg=77 ctermbg=NONE cterm=bold
highlight Cursor guifg=#0c1a0b guibg=#4bf05f guisp=NONE gui=NONE ctermfg=233 ctermbg=83 cterm=NONE
highlight lCursor guifg=#0c1a0b guibg=#4bf05f guisp=NONE gui=NONE ctermfg=233 ctermbg=83 cterm=NONE
highlight CursorLine guifg=NONE guibg=#112510 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#112510 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#112510 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight Visual guifg=#d2e7bd guibg=#1d3d18 guisp=NONE gui=NONE ctermfg=187 ctermbg=235 cterm=NONE
highlight VisualNOS guifg=#d2e7bd guibg=#1d3d18 guisp=NONE gui=NONE ctermfg=187 ctermbg=235 cterm=NONE
highlight Search guifg=#d2e7bd guibg=#214321 guisp=NONE gui=NONE ctermfg=187 ctermbg=236 cterm=NONE
highlight IncSearch guifg=#0c1a0b guibg=#e0c565 guisp=NONE gui=bold ctermfg=233 ctermbg=185 cterm=bold
highlight CurSearch guifg=#0c1a0b guibg=#e0c565 guisp=NONE gui=bold ctermfg=233 ctermbg=185 cterm=bold
highlight Substitute guifg=#0c1a0b guibg=#c45a5a guisp=NONE gui=NONE ctermfg=233 ctermbg=167 cterm=NONE
highlight MatchParen guifg=#e0c565 guibg=#214321 guisp=NONE gui=bold ctermfg=185 ctermbg=236 cterm=bold
highlight LineNr guifg=#6e9f55 guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=71 ctermbg=233 cterm=NONE
highlight LineNrAbove guifg=#6e9f55 guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=71 ctermbg=233 cterm=NONE
highlight LineNrBelow guifg=#6e9f55 guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=71 ctermbg=233 cterm=NONE
highlight CursorLineNr guifg=#56d165 guibg=#112510 guisp=NONE gui=bold ctermfg=77 ctermbg=234 cterm=bold
highlight SignColumn guifg=#99ba86 guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=108 ctermbg=233 cterm=NONE
highlight FoldColumn guifg=#99ba86 guibg=#0c1a0b guisp=NONE gui=NONE ctermfg=108 ctermbg=233 cterm=NONE
highlight Folded guifg=#99ba86 guibg=#112510 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight NonText guifg=#2c4725 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#2c4725 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#2c4725 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#2c4725 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#99ba86 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#d2e7bd guibg=#214321 guisp=NONE gui=bold ctermfg=187 ctermbg=236 cterm=bold
highlight TabLineSel guifg=#d2e7bd guibg=#214321 guisp=NONE gui=bold ctermfg=187 ctermbg=236 cterm=bold
highlight StatusLineNC guifg=#99ba86 guibg=#112510 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight TabLine guifg=#99ba86 guibg=#112510 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight TabLineFill guifg=#99ba86 guibg=#112510 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight WinBarNC guifg=#99ba86 guibg=#112510 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight WinBar guifg=#d2e7bd guibg=#112510 guisp=NONE gui=NONE ctermfg=187 ctermbg=234 cterm=NONE
highlight PmenuSel guifg=#d2e7bd guibg=#214321 guisp=NONE gui=bold ctermfg=187 ctermbg=236 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#112510 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#2c4725 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
highlight PmenuMatch guifg=#56d165 guibg=NONE guisp=NONE gui=bold ctermfg=77 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#56d165 guibg=#214321 guisp=NONE gui=bold ctermfg=77 ctermbg=236 cterm=bold
highlight WildMenu guifg=#0c1a0b guibg=#56d165 guisp=NONE gui=NONE ctermfg=233 ctermbg=77 cterm=NONE
highlight Directory guifg=#7fd05f guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Question guifg=#56d165 guibg=NONE guisp=NONE gui=NONE ctermfg=77 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#56d165 guibg=NONE guisp=NONE gui=NONE ctermfg=77 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#56d165 guibg=NONE guisp=NONE gui=NONE ctermfg=77 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Error guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Comment guifg=#5c794b guibg=NONE guisp=NONE gui=italic ctermfg=65 ctermbg=NONE cterm=italic
highlight Constant guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight String guifg=#e0c565 guibg=NONE guisp=NONE gui=NONE ctermfg=185 ctermbg=NONE cterm=NONE
highlight Character guifg=#e0c565 guibg=NONE guisp=NONE gui=NONE ctermfg=185 ctermbg=NONE cterm=NONE
highlight Number guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Float guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Function guifg=#7fd05f guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Statement guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Label guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Exception guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Operator guifg=#7d9f6e guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#7d9f6e guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Include guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Define guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Macro guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#2ec75a guibg=NONE guisp=NONE gui=NONE ctermfg=41 ctermbg=NONE cterm=NONE
highlight Type guifg=#1fb87a guibg=NONE guisp=NONE gui=NONE ctermfg=36 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#1fb87a guibg=NONE guisp=NONE gui=NONE ctermfg=36 ctermbg=NONE cterm=NONE
highlight Structure guifg=#1fb87a guibg=NONE guisp=NONE gui=NONE ctermfg=36 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#1fb87a guibg=NONE guisp=NONE gui=NONE ctermfg=36 ctermbg=NONE cterm=NONE
highlight Special guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Tag guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Debug guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#5c794b guibg=NONE guisp=NONE gui=bold ctermfg=65 ctermbg=NONE cterm=bold
highlight Underlined guifg=#3dbf9f guibg=NONE guisp=NONE gui=underline ctermfg=73 ctermbg=NONE cterm=underline
highlight Ignore guifg=#6e9f55 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Todo guifg=#e0c565 guibg=#112510 guisp=NONE gui=bold ctermfg=185 ctermbg=234 cterm=bold
highlight DiffAdd guifg=#7fd05f guibg=#112510 guisp=NONE gui=NONE ctermfg=113 ctermbg=234 cterm=NONE
highlight DiffChange guifg=#d1a44e guibg=#112510 guisp=NONE gui=NONE ctermfg=179 ctermbg=234 cterm=NONE
highlight DiffDelete guifg=#c45a5a guibg=#112510 guisp=NONE gui=NONE ctermfg=167 ctermbg=234 cterm=NONE
highlight DiffText guifg=#d2e7bd guibg=#214321 guisp=NONE gui=bold ctermfg=187 ctermbg=236 cterm=bold
highlight diffAdded guifg=#7fd05f guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#c45a5a guibg=#112510 guisp=NONE gui=NONE ctermfg=167 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#d1a44e guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#d1a44e guibg=#112510 guisp=NONE gui=NONE ctermfg=179 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#d1a44e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#3dbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#3dbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#3dbf9f guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#3dbf9f guibg=#112510 guisp=NONE gui=NONE ctermfg=73 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#3dbf9f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#9fd67f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#9fd67f guibg=#112510 guisp=NONE gui=NONE ctermfg=150 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#9fd67f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#7fd05f guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#7fd05f guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#7fd05f guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#7fd05f guibg=#112510 guisp=NONE gui=NONE ctermfg=113 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#7fd05f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#5c794b guibg=NONE guisp=NONE gui=italic ctermfg=65 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#d1a44e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#3dbf9f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#9a7abf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#214321 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#214321 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#214321 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
highlight LspInlayHint guifg=#99ba86 guibg=#112510 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight LspCodeLens guifg=#99ba86 guibg=NONE guisp=NONE gui=italic ctermfg=108 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#9fd67f guibg=NONE guisp=NONE gui=bold,underline ctermfg=150 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#112510', '#c45a5a', '#3dd65a', '#cfae3a', '#1fb87a', '#9a7abf', '#3dbf9f', '#d2e7bd', '#4b6540', '#d47070', '#56d165', '#e0c565', '#3fd0a8', '#b49ad4', '#62c9ae', '#e5f5d3']
