" Kokedera Dusk - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-dusk'

highlight Normal guifg=#c8d8b8 guibg=#121a11 guisp=NONE gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
highlight NormalNC guifg=#c8d8b8 guibg=#121a11 guisp=NONE gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
highlight NormalFloat guifg=#c8d8b8 guibg=#151e14 guisp=NONE gui=NONE ctermfg=187 ctermbg=234 cterm=NONE
highlight Pmenu guifg=#c8d8b8 guibg=#151e14 guisp=NONE gui=NONE ctermfg=187 ctermbg=234 cterm=NONE
highlight FloatBorder guifg=#3a4a35 guibg=#151e14 guisp=NONE gui=NONE ctermfg=237 ctermbg=234 cterm=NONE
highlight WinSeparator guifg=#3a4a35 guibg=#151e14 guisp=NONE gui=NONE ctermfg=237 ctermbg=234 cterm=NONE
highlight VertSplit guifg=#3a4a35 guibg=#151e14 guisp=NONE gui=NONE ctermfg=237 ctermbg=234 cterm=NONE
highlight FloatTitle guifg=#7ec46c guibg=NONE guisp=NONE gui=bold ctermfg=113 ctermbg=NONE cterm=bold
highlight Title guifg=#7ec46c guibg=NONE guisp=NONE gui=bold ctermfg=113 ctermbg=NONE cterm=bold
highlight Cursor guifg=#121a11 guibg=#5ae65a guisp=NONE gui=NONE ctermfg=233 ctermbg=77 cterm=NONE
highlight lCursor guifg=#121a11 guibg=#5ae65a guisp=NONE gui=NONE ctermfg=233 ctermbg=77 cterm=NONE
highlight CursorLine guifg=NONE guibg=#1a2619 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#1a2619 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#1a2619 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight Visual guifg=#c8d8b8 guibg=#2a3d26 guisp=NONE gui=NONE ctermfg=187 ctermbg=236 cterm=NONE
highlight VisualNOS guifg=#c8d8b8 guibg=#2a3d26 guisp=NONE gui=NONE ctermfg=187 ctermbg=236 cterm=NONE
highlight Search guifg=#c8d8b8 guibg=#314530 guisp=NONE gui=NONE ctermfg=187 ctermbg=237 cterm=NONE
highlight IncSearch guifg=#121a11 guibg=#d4c88e guisp=NONE gui=bold ctermfg=233 ctermbg=186 cterm=bold
highlight CurSearch guifg=#121a11 guibg=#d4c88e guisp=NONE gui=bold ctermfg=233 ctermbg=186 cterm=bold
highlight Substitute guifg=#121a11 guibg=#c45a5a guisp=NONE gui=NONE ctermfg=233 ctermbg=167 cterm=NONE
highlight MatchParen guifg=#d4c88e guibg=#314530 guisp=NONE gui=bold ctermfg=186 ctermbg=237 cterm=bold
highlight LineNr guifg=#6d8a5e guibg=#121a11 guisp=NONE gui=NONE ctermfg=65 ctermbg=233 cterm=NONE
highlight LineNrAbove guifg=#6d8a5e guibg=#121a11 guisp=NONE gui=NONE ctermfg=65 ctermbg=233 cterm=NONE
highlight LineNrBelow guifg=#6d8a5e guibg=#121a11 guisp=NONE gui=NONE ctermfg=65 ctermbg=233 cterm=NONE
highlight CursorLineNr guifg=#7ec46c guibg=#1a2619 guisp=NONE gui=bold ctermfg=113 ctermbg=234 cterm=bold
highlight SignColumn guifg=#94aa87 guibg=#121a11 guisp=NONE gui=NONE ctermfg=108 ctermbg=233 cterm=NONE
highlight FoldColumn guifg=#94aa87 guibg=#121a11 guisp=NONE gui=NONE ctermfg=108 ctermbg=233 cterm=NONE
highlight Folded guifg=#94aa87 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight NonText guifg=#3a4a35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#3a4a35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#3a4a35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#3a4a35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#94aa87 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#c8d8b8 guibg=#314530 guisp=NONE gui=bold ctermfg=187 ctermbg=237 cterm=bold
highlight TabLineSel guifg=#c8d8b8 guibg=#314530 guisp=NONE gui=bold ctermfg=187 ctermbg=237 cterm=bold
highlight StatusLineNC guifg=#94aa87 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight TabLine guifg=#94aa87 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight TabLineFill guifg=#94aa87 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight WinBarNC guifg=#94aa87 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight WinBar guifg=#c8d8b8 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=187 ctermbg=234 cterm=NONE
highlight PmenuSel guifg=#c8d8b8 guibg=#314530 guisp=NONE gui=bold ctermfg=187 ctermbg=237 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#1a2619 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#3a4a35 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight PmenuMatch guifg=#7ec46c guibg=NONE guisp=NONE gui=bold ctermfg=113 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#7ec46c guibg=#314530 guisp=NONE gui=bold ctermfg=113 ctermbg=237 cterm=bold
highlight WildMenu guifg=#121a11 guibg=#7ec46c guisp=NONE gui=NONE ctermfg=233 ctermbg=113 cterm=NONE
highlight Directory guifg=#8fbf6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Question guifg=#7ec46c guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#7ec46c guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#7ec46c guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Error guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Comment guifg=#5a6b50 guibg=NONE guisp=NONE gui=italic ctermfg=59 ctermbg=NONE cterm=italic
highlight Constant guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight String guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Character guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Number guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Float guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight Function guifg=#8fbf6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Statement guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Label guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Exception guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Operator guifg=#7a9070 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#7a9070 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Include guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Define guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Macro guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#4ca64c guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Type guifg=#3d9970 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#3d9970 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight Structure guifg=#3d9970 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#3d9970 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight Special guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight Tag guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight Debug guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#5a6b50 guibg=NONE guisp=NONE gui=bold ctermfg=59 ctermbg=NONE cterm=bold
highlight Underlined guifg=#5a9e8f guibg=NONE guisp=NONE gui=underline ctermfg=72 ctermbg=NONE cterm=underline
highlight Ignore guifg=#6d8a5e guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight Todo guifg=#d4c88e guibg=#1a2619 guisp=NONE gui=bold ctermfg=186 ctermbg=234 cterm=bold
highlight DiffAdd guifg=#8fbf6f guibg=#1a2619 guisp=NONE gui=NONE ctermfg=107 ctermbg=234 cterm=NONE
highlight DiffChange guifg=#c49a5c guibg=#1a2619 guisp=NONE gui=NONE ctermfg=173 ctermbg=234 cterm=NONE
highlight DiffDelete guifg=#c45a5a guibg=#1a2619 guisp=NONE gui=NONE ctermfg=167 ctermbg=234 cterm=NONE
highlight DiffText guifg=#c8d8b8 guibg=#314530 guisp=NONE gui=bold ctermfg=187 ctermbg=237 cterm=bold
highlight diffAdded guifg=#8fbf6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#c45a5a guibg=#1a2619 guisp=NONE gui=NONE ctermfg=167 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#c49a5c guibg=#1a2619 guisp=NONE gui=NONE ctermfg=173 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#c49a5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#5a9e8f guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#5a9e8f guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#5a9e8f guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#5a9e8f guibg=#1a2619 guisp=NONE gui=NONE ctermfg=72 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#5a9e8f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#a3be8c guibg=#1a2619 guisp=NONE gui=NONE ctermfg=144 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#a3be8c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#8fbf6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#8fbf6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#8fbf6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#8fbf6f guibg=#1a2619 guisp=NONE gui=NONE ctermfg=107 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#8fbf6f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#5a6b50 guibg=NONE guisp=NONE gui=italic ctermfg=59 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#c49a5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#5a9e8f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#9a7abf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#314530 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#314530 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#314530 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspInlayHint guifg=#94aa87 guibg=#1a2619 guisp=NONE gui=NONE ctermfg=108 ctermbg=234 cterm=NONE
highlight LspCodeLens guifg=#94aa87 guibg=NONE guisp=NONE gui=italic ctermfg=108 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#a3be8c guibg=NONE guisp=NONE gui=bold,underline ctermfg=144 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#1a2619', '#c45a5a', '#5ab85a', '#bfa243', '#3d9970', '#9a7abf', '#5a9e8f', '#c8d8b8', '#4a5a44', '#d47070', '#7ec46c', '#d4c88e', '#5ab89e', '#b49ad4', '#7ab8a8', '#dae8ca']
