" Kokedera Winter - Vim 8+
set background=light
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-winter'

highlight Normal guifg=#323c36 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=237 ctermbg=255 cterm=NONE
highlight NormalNC guifg=#323c36 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=237 ctermbg=255 cterm=NONE
highlight NormalFloat guifg=#323c36 guibg=#e6e9e6 guisp=NONE gui=NONE ctermfg=237 ctermbg=254 cterm=NONE
highlight Pmenu guifg=#323c36 guibg=#e6e9e6 guisp=NONE gui=NONE ctermfg=237 ctermbg=254 cterm=NONE
highlight FloatBorder guifg=#c8cec8 guibg=#e6e9e6 guisp=NONE gui=NONE ctermfg=251 ctermbg=254 cterm=NONE
highlight WinSeparator guifg=#c8cec8 guibg=#e6e9e6 guisp=NONE gui=NONE ctermfg=251 ctermbg=254 cterm=NONE
highlight VertSplit guifg=#c8cec8 guibg=#e6e9e6 guisp=NONE gui=NONE ctermfg=251 ctermbg=254 cterm=NONE
highlight FloatTitle guifg=#2e7a8a guibg=NONE guisp=NONE gui=bold ctermfg=30 ctermbg=NONE cterm=bold
highlight Title guifg=#2e7a8a guibg=NONE guisp=NONE gui=bold ctermfg=30 ctermbg=NONE cterm=bold
highlight Cursor guifg=#eef0ee guibg=#1f8aa8 guisp=NONE gui=NONE ctermfg=255 ctermbg=31 cterm=NONE
highlight lCursor guifg=#eef0ee guibg=#1f8aa8 guisp=NONE gui=NONE ctermfg=255 ctermbg=31 cterm=NONE
highlight CursorLine guifg=NONE guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight Visual guifg=#323c36 guibg=#d4dad4 guisp=NONE gui=NONE ctermfg=237 ctermbg=188 cterm=NONE
highlight VisualNOS guifg=#323c36 guibg=#d4dad4 guisp=NONE gui=NONE ctermfg=237 ctermbg=188 cterm=NONE
highlight Search guifg=#323c36 guibg=#c9d0c9 guisp=NONE gui=NONE ctermfg=237 ctermbg=252 cterm=NONE
highlight IncSearch guifg=#eef0ee guibg=#6b5c2a guisp=NONE gui=bold ctermfg=255 ctermbg=58 cterm=bold
highlight CurSearch guifg=#eef0ee guibg=#6b5c2a guisp=NONE gui=bold ctermfg=255 ctermbg=58 cterm=bold
highlight Substitute guifg=#eef0ee guibg=#a84848 guisp=NONE gui=NONE ctermfg=255 ctermbg=131 cterm=NONE
highlight MatchParen guifg=#6b5c2a guibg=#c9d0c9 guisp=NONE gui=bold ctermfg=58 ctermbg=252 cterm=bold
highlight LineNr guifg=#728a72 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=243 ctermbg=255 cterm=NONE
highlight LineNrAbove guifg=#728a72 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=243 ctermbg=255 cterm=NONE
highlight LineNrBelow guifg=#728a72 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=243 ctermbg=255 cterm=NONE
highlight CursorLineNr guifg=#2e7a8a guibg=#e2e6e2 guisp=NONE gui=bold ctermfg=30 ctermbg=254 cterm=bold
highlight SignColumn guifg=#536152 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=240 ctermbg=255 cterm=NONE
highlight FoldColumn guifg=#536152 guibg=#eef0ee guisp=NONE gui=NONE ctermfg=240 ctermbg=255 cterm=NONE
highlight Folded guifg=#536152 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight NonText guifg=#c8cec8 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#c8cec8 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#c8cec8 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#c8cec8 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#536152 guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#323c36 guibg=#c9d0c9 guisp=NONE gui=bold ctermfg=237 ctermbg=252 cterm=bold
highlight TabLineSel guifg=#323c36 guibg=#c9d0c9 guisp=NONE gui=bold ctermfg=237 ctermbg=252 cterm=bold
highlight StatusLineNC guifg=#536152 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight TabLine guifg=#536152 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight TabLineFill guifg=#536152 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight WinBarNC guifg=#536152 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight WinBar guifg=#323c36 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=237 ctermbg=254 cterm=NONE
highlight PmenuSel guifg=#323c36 guibg=#c9d0c9 guisp=NONE gui=bold ctermfg=237 ctermbg=252 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#c8cec8 guisp=NONE gui=NONE ctermfg=NONE ctermbg=251 cterm=NONE
highlight PmenuMatch guifg=#2e7a8a guibg=NONE guisp=NONE gui=bold ctermfg=30 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#2e7a8a guibg=#c9d0c9 guisp=NONE gui=bold ctermfg=30 ctermbg=252 cterm=bold
highlight WildMenu guifg=#eef0ee guibg=#2e7a8a guisp=NONE gui=NONE ctermfg=255 ctermbg=30 cterm=NONE
highlight Directory guifg=#2f7846 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Question guifg=#2e7a8a guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#2e7a8a guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#2e7a8a guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Error guifg=#a84848 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#a84848 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight Comment guifg=#7d8a80 guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
highlight Constant guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight String guifg=#6b5c2a guibg=NONE guisp=NONE gui=NONE ctermfg=58 ctermbg=NONE cterm=NONE
highlight Character guifg=#6b5c2a guibg=NONE guisp=NONE gui=NONE ctermfg=58 ctermbg=NONE cterm=NONE
highlight Number guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Float guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight Function guifg=#2f7846 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Statement guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Label guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Exception guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Operator guifg=#5e6b62 guibg=NONE guisp=NONE gui=NONE ctermfg=241 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#5e6b62 guibg=NONE guisp=NONE gui=NONE ctermfg=241 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Include guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Define guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Macro guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#25708f guibg=NONE guisp=NONE gui=NONE ctermfg=24 ctermbg=NONE cterm=NONE
highlight Type guifg=#1f7d6b guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#1f7d6b guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight Structure guifg=#1f7d6b guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#1f7d6b guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight Special guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight Tag guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight Debug guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#7d8a80 guibg=NONE guisp=NONE gui=bold ctermfg=244 ctermbg=NONE cterm=bold
highlight Underlined guifg=#357d70 guibg=NONE guisp=NONE gui=underline ctermfg=65 ctermbg=NONE cterm=underline
highlight Ignore guifg=#728a72 guibg=NONE guisp=NONE gui=NONE ctermfg=243 ctermbg=NONE cterm=NONE
highlight Todo guifg=#6b5c2a guibg=#e2e6e2 guisp=NONE gui=bold ctermfg=58 ctermbg=254 cterm=bold
highlight DiffAdd guifg=#2f7846 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=239 ctermbg=254 cterm=NONE
highlight DiffChange guifg=#8a552e guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=94 ctermbg=254 cterm=NONE
highlight DiffDelete guifg=#a84848 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=131 ctermbg=254 cterm=NONE
highlight DiffText guifg=#323c36 guibg=#c9d0c9 guisp=NONE gui=bold ctermfg=237 ctermbg=252 cterm=bold
highlight diffAdded guifg=#2f7846 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#a84848 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#a84848 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#a84848 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#a84848 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#a84848 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=131 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#a84848 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#8a552e guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#8a552e guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=94 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#8a552e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#357d70 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#357d70 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#357d70 guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#357d70 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=65 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#357d70 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#4a6b5c guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#4a6b5c guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#4a6b5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#2f7846 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#2f7846 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#2f7846 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#2f7846 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=239 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#2f7846 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#7d8a80 guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#a84848 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#8a552e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#357d70 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#6b5a9a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#c9d0c9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=252 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#c9d0c9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=252 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#c9d0c9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=252 cterm=NONE
highlight LspInlayHint guifg=#536152 guibg=#e2e6e2 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight LspCodeLens guifg=#536152 guibg=NONE guisp=NONE gui=italic ctermfg=240 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#4a6b5c guibg=NONE guisp=NONE gui=bold,underline ctermfg=240 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#e2e6e2', '#a84848', '#2a7f9c', '#7a6518', '#1f7d6b', '#6b5a9a', '#357d70', '#323c36', '#a2aaa2', '#b85858', '#2e7a8a', '#6b5c2a', '#2a8a75', '#7d6aab', '#4a8a7e', '#222b26']
