" Kokedera Night - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-night'

highlight Normal guifg=#e5eedc guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=254 ctermbg=232 cterm=NONE
highlight NormalNC guifg=#e5eedc guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=254 ctermbg=232 cterm=NONE
highlight NormalFloat guifg=#e5eedc guibg=#0c100b guisp=NONE gui=NONE ctermfg=254 ctermbg=232 cterm=NONE
highlight Pmenu guifg=#e5eedc guibg=#0c100b guisp=NONE gui=NONE ctermfg=254 ctermbg=232 cterm=NONE
highlight FloatBorder guifg=#20291d guibg=#0c100b guisp=NONE gui=NONE ctermfg=235 ctermbg=232 cterm=NONE
highlight WinSeparator guifg=#20291d guibg=#0c100b guisp=NONE gui=NONE ctermfg=235 ctermbg=232 cterm=NONE
highlight VertSplit guifg=#20291d guibg=#0c100b guisp=NONE gui=NONE ctermfg=235 ctermbg=232 cterm=NONE
highlight FloatTitle guifg=#98d787 guibg=NONE guisp=NONE gui=bold ctermfg=114 ctermbg=NONE cterm=bold
highlight Title guifg=#98d787 guibg=NONE guisp=NONE gui=bold ctermfg=114 ctermbg=NONE cterm=bold
highlight Cursor guifg=#0a0e09 guibg=#7bf67b guisp=NONE gui=NONE ctermfg=232 ctermbg=120 cterm=NONE
highlight lCursor guifg=#0a0e09 guibg=#7bf67b guisp=NONE gui=NONE ctermfg=232 ctermbg=120 cterm=NONE
highlight CursorLine guifg=NONE guibg=#0e150e guisp=NONE gui=NONE ctermfg=NONE ctermbg=233 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#0e150e guisp=NONE gui=NONE ctermfg=NONE ctermbg=233 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#0e150e guisp=NONE gui=NONE ctermfg=NONE ctermbg=233 cterm=NONE
highlight Visual guifg=#e5eedc guibg=#172215 guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight VisualNOS guifg=#e5eedc guibg=#172215 guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight Search guifg=#e5eedc guibg=#1b261a guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight IncSearch guifg=#0a0e09 guibg=#e7ddb0 guisp=NONE gui=bold ctermfg=232 ctermbg=187 cterm=bold
highlight CurSearch guifg=#0a0e09 guibg=#e7ddb0 guisp=NONE gui=bold ctermfg=232 ctermbg=187 cterm=bold
highlight Substitute guifg=#0a0e09 guibg=#d77373 guisp=NONE gui=NONE ctermfg=232 ctermbg=167 cterm=NONE
highlight MatchParen guifg=#e7ddb0 guibg=#1b261a guisp=NONE gui=bold ctermfg=187 ctermbg=234 cterm=bold
highlight LineNr guifg=#7ea26c guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=107 ctermbg=232 cterm=NONE
highlight LineNrAbove guifg=#7ea26c guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=107 ctermbg=232 cterm=NONE
highlight LineNrBelow guifg=#7ea26c guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=107 ctermbg=232 cterm=NONE
highlight CursorLineNr guifg=#98d787 guibg=#0e150e guisp=NONE gui=bold ctermfg=114 ctermbg=233 cterm=bold
highlight SignColumn guifg=#acc0a0 guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=145 ctermbg=232 cterm=NONE
highlight FoldColumn guifg=#acc0a0 guibg=#0a0e09 guisp=NONE gui=NONE ctermfg=145 ctermbg=232 cterm=NONE
highlight Folded guifg=#acc0a0 guibg=#0e150e guisp=NONE gui=NONE ctermfg=145 ctermbg=233 cterm=NONE
highlight NonText guifg=#20291d guibg=NONE guisp=NONE gui=NONE ctermfg=235 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#20291d guibg=NONE guisp=NONE gui=NONE ctermfg=235 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#20291d guibg=NONE guisp=NONE gui=NONE ctermfg=235 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#20291d guibg=NONE guisp=NONE gui=NONE ctermfg=235 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#acc0a0 guibg=NONE guisp=NONE gui=NONE ctermfg=145 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#e5eedc guibg=#1b261a guisp=NONE gui=bold ctermfg=254 ctermbg=234 cterm=bold
highlight TabLineSel guifg=#e5eedc guibg=#1b261a guisp=NONE gui=bold ctermfg=254 ctermbg=234 cterm=bold
highlight StatusLineNC guifg=#acc0a0 guibg=#0e150e guisp=NONE gui=NONE ctermfg=145 ctermbg=233 cterm=NONE
highlight TabLine guifg=#acc0a0 guibg=#0e150e guisp=NONE gui=NONE ctermfg=145 ctermbg=233 cterm=NONE
highlight TabLineFill guifg=#acc0a0 guibg=#0e150e guisp=NONE gui=NONE ctermfg=145 ctermbg=233 cterm=NONE
highlight WinBarNC guifg=#acc0a0 guibg=#0e150e guisp=NONE gui=NONE ctermfg=145 ctermbg=233 cterm=NONE
highlight WinBar guifg=#e5eedc guibg=#0e150e guisp=NONE gui=NONE ctermfg=254 ctermbg=233 cterm=NONE
highlight PmenuSel guifg=#e5eedc guibg=#1b261a guisp=NONE gui=bold ctermfg=254 ctermbg=234 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#0e150e guisp=NONE gui=NONE ctermfg=NONE ctermbg=233 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#20291d guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight PmenuMatch guifg=#98d787 guibg=NONE guisp=NONE gui=bold ctermfg=114 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#98d787 guibg=#1b261a guisp=NONE gui=bold ctermfg=114 ctermbg=234 cterm=bold
highlight WildMenu guifg=#0a0e09 guibg=#98d787 guisp=NONE gui=NONE ctermfg=232 ctermbg=114 cterm=NONE
highlight Directory guifg=#a7d38a guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Question guifg=#98d787 guibg=NONE guisp=NONE gui=NONE ctermfg=114 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#98d787 guibg=NONE guisp=NONE gui=NONE ctermfg=114 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#98d787 guibg=NONE guisp=NONE gui=NONE ctermfg=114 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight Error guifg=#d77373 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#d77373 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Comment guifg=#69815b guibg=NONE guisp=NONE gui=italic ctermfg=65 ctermbg=NONE cterm=italic
highlight Constant guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight String guifg=#e7ddb0 guibg=NONE guisp=NONE gui=NONE ctermfg=187 ctermbg=NONE cterm=NONE
highlight Character guifg=#e7ddb0 guibg=NONE guisp=NONE gui=NONE ctermfg=187 ctermbg=NONE cterm=NONE
highlight Number guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight Float guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight Function guifg=#a7d38a guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Statement guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Label guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Exception guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Operator guifg=#8fa485 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#8fa485 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Include guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Define guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Macro guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#5abf5a guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Type guifg=#3ebc84 guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#3ebc84 guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight Structure guifg=#3ebc84 guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#3ebc84 guibg=NONE guisp=NONE gui=NONE ctermfg=72 ctermbg=NONE cterm=NONE
highlight Special guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight Tag guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight Debug guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#69815b guibg=NONE guisp=NONE gui=bold ctermfg=65 ctermbg=NONE cterm=bold
highlight Underlined guifg=#6cb4a4 guibg=NONE guisp=NONE gui=underline ctermfg=73 ctermbg=NONE cterm=underline
highlight Ignore guifg=#7ea26c guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Todo guifg=#e7ddb0 guibg=#0e150e guisp=NONE gui=bold ctermfg=187 ctermbg=233 cterm=bold
highlight DiffAdd guifg=#a7d38a guibg=#0e150e guisp=NONE gui=NONE ctermfg=150 ctermbg=233 cterm=NONE
highlight DiffChange guifg=#d7b075 guibg=#0e150e guisp=NONE gui=NONE ctermfg=180 ctermbg=233 cterm=NONE
highlight DiffDelete guifg=#d77373 guibg=#0e150e guisp=NONE gui=NONE ctermfg=167 ctermbg=233 cterm=NONE
highlight DiffText guifg=#e5eedc guibg=#1b261a guisp=NONE gui=bold ctermfg=254 ctermbg=234 cterm=bold
highlight diffAdded guifg=#a7d38a guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#d77373 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#d77373 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#d77373 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#d77373 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#d77373 guibg=#0e150e guisp=NONE gui=NONE ctermfg=167 ctermbg=233 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#d77373 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#d7b075 guibg=NONE guisp=NONE gui=NONE ctermfg=180 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#d7b075 guibg=#0e150e guisp=NONE gui=NONE ctermfg=180 ctermbg=233 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#d7b075 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#6cb4a4 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#6cb4a4 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#6cb4a4 guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#6cb4a4 guibg=#0e150e guisp=NONE gui=NONE ctermfg=73 ctermbg=233 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#6cb4a4 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#bcd3a9 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#bcd3a9 guibg=#0e150e guisp=NONE gui=NONE ctermfg=151 ctermbg=233 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#bcd3a9 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#a7d38a guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#a7d38a guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#a7d38a guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#a7d38a guibg=#0e150e guisp=NONE gui=NONE ctermfg=150 ctermbg=233 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#a7d38a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#69815b guibg=NONE guisp=NONE gui=italic ctermfg=65 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#d77373 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#d7b075 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#6cb4a4 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#b296d3 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#1b261a guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#1b261a guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#1b261a guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight LspInlayHint guifg=#acc0a0 guibg=#0e150e guisp=NONE gui=NONE ctermfg=145 ctermbg=233 cterm=NONE
highlight LspCodeLens guifg=#acc0a0 guibg=NONE guisp=NONE gui=italic ctermfg=145 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#bcd3a9 guibg=NONE guisp=NONE gui=bold,underline ctermfg=151 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#0e150e', '#d77373', '#71cc71', '#d3b658', '#3ebc84', '#b296d3', '#6cb4a4', '#e5eedc', '#4a5a44', '#e68f8f', '#98d787', '#e7ddb0', '#71ccb3', '#d0bde7', '#94cdbe', '#ebf4e1']
