" Kokedera Morning - Vim 8+
set background=light
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-morning'

highlight Normal guifg=#333f2c guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=236 ctermbg=255 cterm=NONE
highlight NormalNC guifg=#333f2c guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=236 ctermbg=255 cterm=NONE
highlight NormalFloat guifg=#333f2c guibg=#edeadb guisp=NONE gui=NONE ctermfg=236 ctermbg=254 cterm=NONE
highlight Pmenu guifg=#333f2c guibg=#edeadb guisp=NONE gui=NONE ctermfg=236 ctermbg=254 cterm=NONE
highlight FloatBorder guifg=#d5d2c0 guibg=#edeadb guisp=NONE gui=NONE ctermfg=252 ctermbg=254 cterm=NONE
highlight WinSeparator guifg=#d5d2c0 guibg=#edeadb guisp=NONE gui=NONE ctermfg=252 ctermbg=254 cterm=NONE
highlight VertSplit guifg=#d5d2c0 guibg=#edeadb guisp=NONE gui=NONE ctermfg=252 ctermbg=254 cterm=NONE
highlight FloatTitle guifg=#3b8a3c guibg=NONE guisp=NONE gui=bold ctermfg=65 ctermbg=NONE cterm=bold
highlight Title guifg=#3b8a3c guibg=NONE guisp=NONE gui=bold ctermfg=65 ctermbg=NONE cterm=bold
highlight Cursor guifg=#f4f2e6 guibg=#27ae37 guisp=NONE gui=NONE ctermfg=255 ctermbg=35 cterm=NONE
highlight lCursor guifg=#f4f2e6 guibg=#27ae37 guisp=NONE gui=NONE ctermfg=255 ctermbg=35 cterm=NONE
highlight CursorLine guifg=NONE guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight Visual guifg=#333f2c guibg=#e0ddc8 guisp=NONE gui=NONE ctermfg=236 ctermbg=188 cterm=NONE
highlight VisualNOS guifg=#333f2c guibg=#e0ddc8 guisp=NONE gui=NONE ctermfg=236 ctermbg=188 cterm=NONE
highlight Search guifg=#333f2c guibg=#d6d3bd guisp=NONE gui=NONE ctermfg=236 ctermbg=187 cterm=NONE
highlight IncSearch guifg=#f4f2e6 guibg=#75641a guisp=NONE gui=bold ctermfg=255 ctermbg=94 cterm=bold
highlight CurSearch guifg=#f4f2e6 guibg=#75641a guisp=NONE gui=bold ctermfg=255 ctermbg=94 cterm=bold
highlight Substitute guifg=#f4f2e6 guibg=#b03a3a guisp=NONE gui=NONE ctermfg=255 ctermbg=131 cterm=NONE
highlight MatchParen guifg=#75641a guibg=#d6d3bd guisp=NONE gui=bold ctermfg=94 ctermbg=187 cterm=bold
highlight LineNr guifg=#779666 guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=101 ctermbg=255 cterm=NONE
highlight LineNrAbove guifg=#779666 guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=101 ctermbg=255 cterm=NONE
highlight LineNrBelow guifg=#779666 guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=101 ctermbg=255 cterm=NONE
highlight CursorLineNr guifg=#3b8a3c guibg=#ece9d8 guisp=NONE gui=bold ctermfg=65 ctermbg=254 cterm=bold
highlight SignColumn guifg=#56694a guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=240 ctermbg=255 cterm=NONE
highlight FoldColumn guifg=#56694a guibg=#f4f2e6 guisp=NONE gui=NONE ctermfg=240 ctermbg=255 cterm=NONE
highlight Folded guifg=#56694a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight NonText guifg=#d5d2c0 guibg=NONE guisp=NONE gui=NONE ctermfg=252 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#d5d2c0 guibg=NONE guisp=NONE gui=NONE ctermfg=252 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#d5d2c0 guibg=NONE guisp=NONE gui=NONE ctermfg=252 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#d5d2c0 guibg=NONE guisp=NONE gui=NONE ctermfg=252 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#56694a guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#333f2c guibg=#d6d3bd guisp=NONE gui=bold ctermfg=236 ctermbg=187 cterm=bold
highlight TabLineSel guifg=#333f2c guibg=#d6d3bd guisp=NONE gui=bold ctermfg=236 ctermbg=187 cterm=bold
highlight StatusLineNC guifg=#56694a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight TabLine guifg=#56694a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight TabLineFill guifg=#56694a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight WinBarNC guifg=#56694a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight WinBar guifg=#333f2c guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=236 ctermbg=254 cterm=NONE
highlight PmenuSel guifg=#333f2c guibg=#d6d3bd guisp=NONE gui=bold ctermfg=236 ctermbg=187 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=NONE ctermbg=254 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#d5d2c0 guisp=NONE gui=NONE ctermfg=NONE ctermbg=252 cterm=NONE
highlight PmenuMatch guifg=#3b8a3c guibg=NONE guisp=NONE gui=bold ctermfg=65 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#3b8a3c guibg=#d6d3bd guisp=NONE gui=bold ctermfg=65 ctermbg=187 cterm=bold
highlight WildMenu guifg=#f4f2e6 guibg=#3b8a3c guisp=NONE gui=NONE ctermfg=255 ctermbg=65 cterm=NONE
highlight Directory guifg=#487612 guibg=NONE guisp=NONE gui=NONE ctermfg=64 ctermbg=NONE cterm=NONE
highlight Question guifg=#3b8a3c guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#3b8a3c guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#3b8a3c guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Error guifg=#b03a3a guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#b03a3a guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight Comment guifg=#828e6e guibg=NONE guisp=NONE gui=italic ctermfg=101 ctermbg=NONE cterm=italic
highlight Constant guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight String guifg=#75641a guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Character guifg=#75641a guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Number guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Float guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Function guifg=#487612 guibg=NONE guisp=NONE gui=NONE ctermfg=64 ctermbg=NONE cterm=NONE
highlight Statement guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Label guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Exception guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Operator guifg=#6b7a5e guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#6b7a5e guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Include guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Define guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Macro guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#2e7d32 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Type guifg=#1d7a5c guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#1d7a5c guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight Structure guifg=#1d7a5c guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#1d7a5c guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE cterm=NONE
highlight Special guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Tag guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Debug guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#828e6e guibg=NONE guisp=NONE gui=bold ctermfg=101 ctermbg=NONE cterm=bold
highlight Underlined guifg=#3d7a6c guibg=NONE guisp=NONE gui=underline ctermfg=65 ctermbg=NONE cterm=underline
highlight Ignore guifg=#779666 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
highlight Todo guifg=#75641a guibg=#ece9d8 guisp=NONE gui=bold ctermfg=94 ctermbg=254 cterm=bold
highlight DiffAdd guifg=#487612 guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=64 ctermbg=254 cterm=NONE
highlight DiffChange guifg=#99541d guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=94 ctermbg=254 cterm=NONE
highlight DiffDelete guifg=#b03a3a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=131 ctermbg=254 cterm=NONE
highlight DiffText guifg=#333f2c guibg=#d6d3bd guisp=NONE gui=bold ctermfg=236 ctermbg=187 cterm=bold
highlight diffAdded guifg=#487612 guibg=NONE guisp=NONE gui=NONE ctermfg=64 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#b03a3a guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#b03a3a guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#b03a3a guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#b03a3a guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#b03a3a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=131 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#b03a3a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#99541d guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#99541d guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=94 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#99541d gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#3d7a6c guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#3d7a6c guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#3d7a6c guibg=NONE guisp=NONE gui=NONE ctermfg=65 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#3d7a6c guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=65 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#3d7a6c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#4a6b2e guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#4a6b2e guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=239 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#4a6b2e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#487612 guibg=NONE guisp=NONE gui=NONE ctermfg=64 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#487612 guibg=NONE guisp=NONE gui=NONE ctermfg=64 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#487612 guibg=NONE guisp=NONE gui=NONE ctermfg=64 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#487612 guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=64 ctermbg=254 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#487612 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#828e6e guibg=NONE guisp=NONE gui=italic ctermfg=101 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#b03a3a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#99541d gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#3d7a6c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#7a4fa8 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#d6d3bd guisp=NONE gui=NONE ctermfg=NONE ctermbg=187 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#d6d3bd guisp=NONE gui=NONE ctermfg=NONE ctermbg=187 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#d6d3bd guisp=NONE gui=NONE ctermfg=NONE ctermbg=187 cterm=NONE
highlight LspInlayHint guifg=#56694a guibg=#ece9d8 guisp=NONE gui=NONE ctermfg=240 ctermbg=254 cterm=NONE
highlight LspCodeLens guifg=#56694a guibg=NONE guisp=NONE gui=italic ctermfg=240 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#4a6b2e guibg=NONE guisp=NONE gui=bold,underline ctermfg=239 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#ece9d8', '#b03a3a', '#349a3c', '#87691a', '#1d7a5c', '#7a4fa8', '#3d7a6c', '#333f2c', '#a8a492', '#c25050', '#3b8a3c', '#75641a', '#2e8a6e', '#8a5fb8', '#4a8a7a', '#222b1c']
