" Kokedera Mist - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-mist'

highlight Normal guifg=#aab69e guibg=#191e19 guisp=NONE gui=NONE ctermfg=248 ctermbg=234 cterm=NONE
highlight NormalNC guifg=#aab69e guibg=#191e19 guisp=NONE gui=NONE ctermfg=248 ctermbg=234 cterm=NONE
highlight NormalFloat guifg=#aab69e guibg=#1d221c guisp=NONE gui=NONE ctermfg=248 ctermbg=234 cterm=NONE
highlight Pmenu guifg=#aab69e guibg=#1d221c guisp=NONE gui=NONE ctermfg=248 ctermbg=234 cterm=NONE
highlight FloatBorder guifg=#495146 guibg=#1d221c guisp=NONE gui=NONE ctermfg=239 ctermbg=234 cterm=NONE
highlight WinSeparator guifg=#495146 guibg=#1d221c guisp=NONE gui=NONE ctermfg=239 ctermbg=234 cterm=NONE
highlight VertSplit guifg=#495146 guibg=#1d221c guisp=NONE gui=NONE ctermfg=239 ctermbg=234 cterm=NONE
highlight FloatTitle guifg=#8ab383 guibg=NONE guisp=NONE gui=bold ctermfg=108 ctermbg=NONE cterm=bold
highlight Title guifg=#8ab383 guibg=NONE guisp=NONE gui=bold ctermfg=108 ctermbg=NONE cterm=bold
highlight Cursor guifg=#191e19 guibg=#7dbf7d guisp=NONE gui=NONE ctermfg=234 ctermbg=108 cterm=NONE
highlight lCursor guifg=#191e19 guibg=#7dbf7d guisp=NONE gui=NONE ctermfg=234 ctermbg=108 cterm=NONE
highlight CursorLine guifg=NONE guibg=#242a23 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#242a23 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#242a23 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight Visual guifg=#aab69e guibg=#374235 guisp=NONE gui=NONE ctermfg=248 ctermbg=237 cterm=NONE
highlight VisualNOS guifg=#aab69e guibg=#374235 guisp=NONE gui=NONE ctermfg=248 ctermbg=237 cterm=NONE
highlight Search guifg=#aab69e guibg=#414b40 guisp=NONE gui=NONE ctermfg=248 ctermbg=238 cterm=NONE
highlight IncSearch guifg=#191e19 guibg=#b5a97e guisp=NONE gui=bold ctermfg=234 ctermbg=144 cterm=bold
highlight CurSearch guifg=#191e19 guibg=#b5a97e guisp=NONE gui=bold ctermfg=234 ctermbg=144 cterm=bold
highlight Substitute guifg=#191e19 guibg=#a87373 guisp=NONE gui=NONE ctermfg=234 ctermbg=131 cterm=NONE
highlight MatchParen guifg=#b5a97e guibg=#414b40 guisp=NONE gui=bold ctermfg=144 ctermbg=238 cterm=bold
highlight LineNr guifg=#7c8c74 guibg=#191e19 guisp=NONE gui=NONE ctermfg=244 ctermbg=234 cterm=NONE
highlight LineNrAbove guifg=#7c8c74 guibg=#191e19 guisp=NONE gui=NONE ctermfg=244 ctermbg=234 cterm=NONE
highlight LineNrBelow guifg=#7c8c74 guibg=#191e19 guisp=NONE gui=NONE ctermfg=244 ctermbg=234 cterm=NONE
highlight CursorLineNr guifg=#8ab383 guibg=#242a23 guisp=NONE gui=bold ctermfg=108 ctermbg=235 cterm=bold
highlight SignColumn guifg=#909c89 guibg=#191e19 guisp=NONE gui=NONE ctermfg=246 ctermbg=234 cterm=NONE
highlight FoldColumn guifg=#909c89 guibg=#191e19 guisp=NONE gui=NONE ctermfg=246 ctermbg=234 cterm=NONE
highlight Folded guifg=#909c89 guibg=#242a23 guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
highlight NonText guifg=#495146 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#495146 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#495146 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#495146 guibg=NONE guisp=NONE gui=NONE ctermfg=239 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#909c89 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#aab69e guibg=#414b40 guisp=NONE gui=bold ctermfg=248 ctermbg=238 cterm=bold
highlight TabLineSel guifg=#aab69e guibg=#414b40 guisp=NONE gui=bold ctermfg=248 ctermbg=238 cterm=bold
highlight StatusLineNC guifg=#909c89 guibg=#242a23 guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
highlight TabLine guifg=#909c89 guibg=#242a23 guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
highlight TabLineFill guifg=#909c89 guibg=#242a23 guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
highlight WinBarNC guifg=#909c89 guibg=#242a23 guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
highlight WinBar guifg=#aab69e guibg=#242a23 guisp=NONE gui=NONE ctermfg=248 ctermbg=235 cterm=NONE
highlight PmenuSel guifg=#aab69e guibg=#414b40 guisp=NONE gui=bold ctermfg=248 ctermbg=238 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#242a23 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#495146 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
highlight PmenuMatch guifg=#8ab383 guibg=NONE guisp=NONE gui=bold ctermfg=108 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#8ab383 guibg=#414b40 guisp=NONE gui=bold ctermfg=108 ctermbg=238 cterm=bold
highlight WildMenu guifg=#191e19 guibg=#8ab383 guisp=NONE gui=NONE ctermfg=234 ctermbg=108 cterm=NONE
highlight Directory guifg=#85ab6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Question guifg=#8ab383 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#8ab383 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#8ab383 guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Error guifg=#a87373 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#a87373 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight Comment guifg=#737d6c guibg=NONE guisp=NONE gui=italic ctermfg=243 ctermbg=NONE cterm=italic
highlight Constant guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight String guifg=#b5a97e guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight Character guifg=#b5a97e guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight Number guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Float guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight Function guifg=#85ab6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Statement guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Label guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Exception guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Operator guifg=#838e7f guibg=NONE guisp=NONE gui=NONE ctermfg=102 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#838e7f guibg=NONE guisp=NONE gui=NONE ctermfg=102 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Include guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Define guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Macro guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#6ba263 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE
highlight Type guifg=#6b8fa6 guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#6b8fa6 guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight Structure guifg=#6b8fa6 guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#6b8fa6 guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
highlight Special guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight Tag guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight Debug guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#737d6c guibg=NONE guisp=NONE gui=bold ctermfg=243 ctermbg=NONE cterm=bold
highlight Underlined guifg=#7b98a8 guibg=NONE guisp=NONE gui=underline ctermfg=103 ctermbg=NONE cterm=underline
highlight Ignore guifg=#7c8c74 guibg=NONE guisp=NONE gui=NONE ctermfg=244 ctermbg=NONE cterm=NONE
highlight Todo guifg=#b5a97e guibg=#242a23 guisp=NONE gui=bold ctermfg=144 ctermbg=235 cterm=bold
highlight DiffAdd guifg=#85ab6f guibg=#242a23 guisp=NONE gui=NONE ctermfg=107 ctermbg=235 cterm=NONE
highlight DiffChange guifg=#b08e6a guibg=#242a23 guisp=NONE gui=NONE ctermfg=137 ctermbg=235 cterm=NONE
highlight DiffDelete guifg=#a87373 guibg=#242a23 guisp=NONE gui=NONE ctermfg=131 ctermbg=235 cterm=NONE
highlight DiffText guifg=#aab69e guibg=#414b40 guisp=NONE gui=bold ctermfg=248 ctermbg=238 cterm=bold
highlight diffAdded guifg=#85ab6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#a87373 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#a87373 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#a87373 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#a87373 guibg=NONE guisp=NONE gui=NONE ctermfg=131 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#a87373 guibg=#242a23 guisp=NONE gui=NONE ctermfg=131 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#a87373 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#b08e6a guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#b08e6a guibg=#242a23 guisp=NONE gui=NONE ctermfg=137 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#b08e6a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#7b98a8 guibg=NONE guisp=NONE gui=NONE ctermfg=103 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#7b98a8 guibg=NONE guisp=NONE gui=NONE ctermfg=103 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#7b98a8 guibg=NONE guisp=NONE gui=NONE ctermfg=103 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#7b98a8 guibg=#242a23 guisp=NONE gui=NONE ctermfg=103 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#7b98a8 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#a8b49b guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#a8b49b guibg=#242a23 guisp=NONE gui=NONE ctermfg=248 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#a8b49b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#85ab6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#85ab6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#85ab6f guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#85ab6f guibg=#242a23 guisp=NONE gui=NONE ctermfg=107 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#85ab6f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#737d6c guibg=NONE guisp=NONE gui=italic ctermfg=243 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#a87373 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#b08e6a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#7b98a8 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#9787ab gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#414b40 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#414b40 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#414b40 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
highlight LspInlayHint guifg=#909c89 guibg=#242a23 guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
highlight LspCodeLens guifg=#909c89 guibg=NONE guisp=NONE gui=italic ctermfg=246 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#a8b49b guibg=NONE guisp=NONE gui=bold,underline ctermfg=248 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#242a23', '#a87373', '#74ab6c', '#a8935a', '#6b8fa6', '#9787ab', '#7b98a8', '#aab69e', '#6a7566', '#b37b7b', '#8ab383', '#b5a97e', '#7ba093', '#a396bd', '#8faca4', '#dae0d2']
