" Kokedera Spring - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-spring'

highlight Normal guifg=#e7ead6 guibg=#1b2317 guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight NormalNC guifg=#e7ead6 guibg=#1b2317 guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight NormalFloat guifg=#e7ead6 guibg=#1f291b guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight Pmenu guifg=#e7ead6 guibg=#1f291b guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
highlight FloatBorder guifg=#546547 guibg=#1f291b guisp=NONE gui=NONE ctermfg=240 ctermbg=234 cterm=NONE
highlight WinSeparator guifg=#546547 guibg=#1f291b guisp=NONE gui=NONE ctermfg=240 ctermbg=234 cterm=NONE
highlight VertSplit guifg=#546547 guibg=#1f291b guisp=NONE gui=NONE ctermfg=240 ctermbg=234 cterm=NONE
highlight FloatTitle guifg=#97d45e guibg=NONE guisp=NONE gui=bold ctermfg=113 ctermbg=NONE cterm=bold
highlight Title guifg=#97d45e guibg=NONE guisp=NONE gui=bold ctermfg=113 ctermbg=NONE cterm=bold
highlight Cursor guifg=#1b2317 guibg=#8ee65a guisp=NONE gui=NONE ctermfg=234 ctermbg=113 cterm=NONE
highlight lCursor guifg=#1b2317 guibg=#8ee65a guisp=NONE gui=NONE ctermfg=234 ctermbg=113 cterm=NONE
highlight CursorLine guifg=NONE guibg=#263421 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#263421 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#263421 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight Visual guifg=#e7ead6 guibg=#3f5333 guisp=NONE gui=NONE ctermfg=254 ctermbg=238 cterm=NONE
highlight VisualNOS guifg=#e7ead6 guibg=#3f5333 guisp=NONE gui=NONE ctermfg=254 ctermbg=238 cterm=NONE
highlight Search guifg=#e7ead6 guibg=#475e40 guisp=NONE gui=NONE ctermfg=254 ctermbg=239 cterm=NONE
highlight IncSearch guifg=#1b2317 guibg=#d4c88e guisp=NONE gui=bold ctermfg=234 ctermbg=186 cterm=bold
highlight CurSearch guifg=#1b2317 guibg=#d4c88e guisp=NONE gui=bold ctermfg=234 ctermbg=186 cterm=bold
highlight Substitute guifg=#1b2317 guibg=#c45a5a guisp=NONE gui=NONE ctermfg=234 ctermbg=167 cterm=NONE
highlight MatchParen guifg=#d4c88e guibg=#475e40 guisp=NONE gui=bold ctermfg=186 ctermbg=239 cterm=bold
highlight LineNr guifg=#8b9d67 guibg=#1b2317 guisp=NONE gui=NONE ctermfg=107 ctermbg=234 cterm=NONE
highlight LineNrAbove guifg=#8b9d67 guibg=#1b2317 guisp=NONE gui=NONE ctermfg=107 ctermbg=234 cterm=NONE
highlight LineNrBelow guifg=#8b9d67 guibg=#1b2317 guisp=NONE gui=NONE ctermfg=107 ctermbg=234 cterm=NONE
highlight CursorLineNr guifg=#97d45e guibg=#263421 guisp=NONE gui=bold ctermfg=113 ctermbg=235 cterm=bold
highlight SignColumn guifg=#b2bb9a guibg=#1b2317 guisp=NONE gui=NONE ctermfg=144 ctermbg=234 cterm=NONE
highlight FoldColumn guifg=#b2bb9a guibg=#1b2317 guisp=NONE gui=NONE ctermfg=144 ctermbg=234 cterm=NONE
highlight Folded guifg=#b2bb9a guibg=#263421 guisp=NONE gui=NONE ctermfg=144 ctermbg=235 cterm=NONE
highlight NonText guifg=#546547 guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#546547 guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#546547 guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#546547 guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#b2bb9a guibg=NONE guisp=NONE gui=NONE ctermfg=144 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#e7ead6 guibg=#475e40 guisp=NONE gui=bold ctermfg=254 ctermbg=239 cterm=bold
highlight TabLineSel guifg=#e7ead6 guibg=#475e40 guisp=NONE gui=bold ctermfg=254 ctermbg=239 cterm=bold
highlight StatusLineNC guifg=#b2bb9a guibg=#263421 guisp=NONE gui=NONE ctermfg=144 ctermbg=235 cterm=NONE
highlight TabLine guifg=#b2bb9a guibg=#263421 guisp=NONE gui=NONE ctermfg=144 ctermbg=235 cterm=NONE
highlight TabLineFill guifg=#b2bb9a guibg=#263421 guisp=NONE gui=NONE ctermfg=144 ctermbg=235 cterm=NONE
highlight WinBarNC guifg=#b2bb9a guibg=#263421 guisp=NONE gui=NONE ctermfg=144 ctermbg=235 cterm=NONE
highlight WinBar guifg=#e7ead6 guibg=#263421 guisp=NONE gui=NONE ctermfg=254 ctermbg=235 cterm=NONE
highlight PmenuSel guifg=#e7ead6 guibg=#475e40 guisp=NONE gui=bold ctermfg=254 ctermbg=239 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#263421 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#546547 guisp=NONE gui=NONE ctermfg=NONE ctermbg=240 cterm=NONE
highlight PmenuMatch guifg=#97d45e guibg=NONE guisp=NONE gui=bold ctermfg=113 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#97d45e guibg=#475e40 guisp=NONE gui=bold ctermfg=113 ctermbg=239 cterm=bold
highlight WildMenu guifg=#1b2317 guibg=#97d45e guisp=NONE gui=NONE ctermfg=234 ctermbg=113 cterm=NONE
highlight Directory guifg=#a8d072 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
highlight Question guifg=#97d45e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#97d45e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#97d45e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Error guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Comment guifg=#707a57 guibg=NONE guisp=NONE gui=italic ctermfg=65 ctermbg=NONE cterm=italic
highlight Constant guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight String guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Character guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Number guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Float guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Function guifg=#a8d072 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
highlight Statement guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Label guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Exception guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Operator guifg=#94a07f guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#94a07f guibg=NONE guisp=NONE gui=NONE ctermfg=108 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Include guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Define guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Macro guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#7ac93e guibg=NONE guisp=NONE gui=NONE ctermfg=113 ctermbg=NONE cterm=NONE
highlight Type guifg=#d98a9e guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#d98a9e guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight Structure guifg=#d98a9e guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#d98a9e guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight Special guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Tag guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight Debug guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#707a57 guibg=NONE guisp=NONE gui=bold ctermfg=65 ctermbg=NONE cterm=bold
highlight Underlined guifg=#c98ba0 guibg=NONE guisp=NONE gui=underline ctermfg=175 ctermbg=NONE cterm=underline
highlight Ignore guifg=#8b9d67 guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
highlight Todo guifg=#d4c88e guibg=#263421 guisp=NONE gui=bold ctermfg=186 ctermbg=235 cterm=bold
highlight DiffAdd guifg=#a8d072 guibg=#263421 guisp=NONE gui=NONE ctermfg=149 ctermbg=235 cterm=NONE
highlight DiffChange guifg=#c49a5c guibg=#263421 guisp=NONE gui=NONE ctermfg=173 ctermbg=235 cterm=NONE
highlight DiffDelete guifg=#c45a5a guibg=#263421 guisp=NONE gui=NONE ctermfg=167 ctermbg=235 cterm=NONE
highlight DiffText guifg=#e7ead6 guibg=#475e40 guisp=NONE gui=bold ctermfg=254 ctermbg=239 cterm=bold
highlight diffAdded guifg=#a8d072 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#c45a5a guibg=#263421 guisp=NONE gui=NONE ctermfg=167 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#c49a5c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#c49a5c guibg=#263421 guisp=NONE gui=NONE ctermfg=173 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#c49a5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#c98ba0 guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#c98ba0 guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#c98ba0 guibg=NONE guisp=NONE gui=NONE ctermfg=175 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#c98ba0 guibg=#263421 guisp=NONE gui=NONE ctermfg=175 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#c98ba0 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#bad892 guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#bad892 guibg=#263421 guisp=NONE gui=NONE ctermfg=150 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#bad892 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#a8d072 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#a8d072 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#a8d072 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#a8d072 guibg=#263421 guisp=NONE gui=NONE ctermfg=149 ctermbg=235 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#a8d072 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#707a57 guibg=NONE guisp=NONE gui=italic ctermfg=65 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#c49a5c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#c98ba0 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#9a7abf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#475e40 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#475e40 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#475e40 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
highlight LspInlayHint guifg=#b2bb9a guibg=#263421 guisp=NONE gui=NONE ctermfg=144 ctermbg=235 cterm=NONE
highlight LspCodeLens guifg=#b2bb9a guibg=NONE guisp=NONE gui=italic ctermfg=144 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#bad892 guibg=NONE guisp=NONE gui=bold,underline ctermfg=150 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#263421', '#c45a5a', '#85d44c', '#bfa243', '#d98a9e', '#9a7abf', '#c98ba0', '#e7ead6', '#5b674a', '#d47070', '#97d45e', '#d4c88e', '#d494a8', '#b49ad4', '#cfa0b0', '#eef1da']
