" Kokedera Autumn - Vim 8+
set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'kokedera-autumn'

highlight Normal guifg=#d8c1b8 guibg=#1a1511 guisp=NONE gui=NONE ctermfg=181 ctermbg=233 cterm=NONE
highlight NormalNC guifg=#d8c1b8 guibg=#1a1511 guisp=NONE gui=NONE ctermfg=181 ctermbg=233 cterm=NONE
highlight NormalFloat guifg=#d8c1b8 guibg=#1e1814 guisp=NONE gui=NONE ctermfg=181 ctermbg=234 cterm=NONE
highlight Pmenu guifg=#d8c1b8 guibg=#1e1814 guisp=NONE gui=NONE ctermfg=181 ctermbg=234 cterm=NONE
highlight FloatBorder guifg=#4a3e35 guibg=#1e1814 guisp=NONE gui=NONE ctermfg=237 ctermbg=234 cterm=NONE
highlight WinSeparator guifg=#4a3e35 guibg=#1e1814 guisp=NONE gui=NONE ctermfg=237 ctermbg=234 cterm=NONE
highlight VertSplit guifg=#4a3e35 guibg=#1e1814 guisp=NONE gui=NONE ctermfg=237 ctermbg=234 cterm=NONE
highlight FloatTitle guifg=#c48c6c guibg=NONE guisp=NONE gui=bold ctermfg=173 ctermbg=NONE cterm=bold
highlight Title guifg=#c48c6c guibg=NONE guisp=NONE gui=bold ctermfg=173 ctermbg=NONE cterm=bold
highlight Cursor guifg=#1a1511 guibg=#e6945a guisp=NONE gui=NONE ctermfg=233 ctermbg=173 cterm=NONE
highlight lCursor guifg=#1a1511 guibg=#e6945a guisp=NONE gui=NONE ctermfg=233 ctermbg=173 cterm=NONE
highlight CursorLine guifg=NONE guibg=#261e19 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight CursorColumn guifg=NONE guibg=#261e19 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight ColorColumn guifg=NONE guibg=#261e19 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight Visual guifg=#d8c1b8 guibg=#3d3026 guisp=NONE gui=NONE ctermfg=181 ctermbg=236 cterm=NONE
highlight VisualNOS guifg=#d8c1b8 guibg=#3d3026 guisp=NONE gui=NONE ctermfg=181 ctermbg=236 cterm=NONE
highlight Search guifg=#d8c1b8 guibg=#453930 guisp=NONE gui=NONE ctermfg=181 ctermbg=237 cterm=NONE
highlight IncSearch guifg=#1a1511 guibg=#d4c88e guisp=NONE gui=bold ctermfg=233 ctermbg=186 cterm=bold
highlight CurSearch guifg=#1a1511 guibg=#d4c88e guisp=NONE gui=bold ctermfg=233 ctermbg=186 cterm=bold
highlight Substitute guifg=#1a1511 guibg=#c45a5a guisp=NONE gui=NONE ctermfg=233 ctermbg=167 cterm=NONE
highlight MatchParen guifg=#d4c88e guibg=#453930 guisp=NONE gui=bold ctermfg=186 ctermbg=237 cterm=bold
highlight LineNr guifg=#8a6d5e guibg=#1a1511 guisp=NONE gui=NONE ctermfg=95 ctermbg=233 cterm=NONE
highlight LineNrAbove guifg=#8a6d5e guibg=#1a1511 guisp=NONE gui=NONE ctermfg=95 ctermbg=233 cterm=NONE
highlight LineNrBelow guifg=#8a6d5e guibg=#1a1511 guisp=NONE gui=NONE ctermfg=95 ctermbg=233 cterm=NONE
highlight CursorLineNr guifg=#c48c6c guibg=#261e19 guisp=NONE gui=bold ctermfg=173 ctermbg=234 cterm=bold
highlight SignColumn guifg=#aa9287 guibg=#1a1511 guisp=NONE gui=NONE ctermfg=138 ctermbg=233 cterm=NONE
highlight FoldColumn guifg=#aa9287 guibg=#1a1511 guisp=NONE gui=NONE ctermfg=138 ctermbg=233 cterm=NONE
highlight Folded guifg=#aa9287 guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight NonText guifg=#4a3e35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight EndOfBuffer guifg=#4a3e35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight Whitespace guifg=#4a3e35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight SpecialKey guifg=#4a3e35 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
highlight Conceal guifg=#aa9287 guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight StatusLine guifg=#d8c1b8 guibg=#453930 guisp=NONE gui=bold ctermfg=181 ctermbg=237 cterm=bold
highlight TabLineSel guifg=#d8c1b8 guibg=#453930 guisp=NONE gui=bold ctermfg=181 ctermbg=237 cterm=bold
highlight StatusLineNC guifg=#aa9287 guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight TabLine guifg=#aa9287 guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight TabLineFill guifg=#aa9287 guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight WinBarNC guifg=#aa9287 guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight WinBar guifg=#d8c1b8 guibg=#261e19 guisp=NONE gui=NONE ctermfg=181 ctermbg=234 cterm=NONE
highlight PmenuSel guifg=#d8c1b8 guibg=#453930 guisp=NONE gui=bold ctermfg=181 ctermbg=237 cterm=bold
highlight PmenuSbar guifg=NONE guibg=#261e19 guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#4a3e35 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight PmenuMatch guifg=#c48c6c guibg=NONE guisp=NONE gui=bold ctermfg=173 ctermbg=NONE cterm=bold
highlight PmenuMatchSel guifg=#c48c6c guibg=#453930 guisp=NONE gui=bold ctermfg=173 ctermbg=237 cterm=bold
highlight WildMenu guifg=#1a1511 guibg=#c48c6c guisp=NONE gui=NONE ctermfg=233 ctermbg=173 cterm=NONE
highlight Directory guifg=#bf886f guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Question guifg=#c48c6c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight MoreMsg guifg=#c48c6c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight ModeMsg guifg=#c48c6c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight WarningMsg guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Error guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight ErrorMsg guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Comment guifg=#7d6a56 guibg=NONE guisp=NONE gui=italic ctermfg=95 ctermbg=NONE cterm=italic
highlight Constant guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight String guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Character guifg=#d4c88e guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
highlight Number guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Float guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Boolean guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight Identifier guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight Function guifg=#bf886f guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Statement guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Conditional guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Repeat guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Label guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Keyword guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Exception guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Operator guifg=#907b70 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
highlight Delimiter guifg=#907b70 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
highlight PreProc guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Include guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Define guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Macro guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight PreCondit guifg=#b57e55 guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight Type guifg=#c76c48 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight StorageClass guifg=#c76c48 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Structure guifg=#c76c48 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Typedef guifg=#c76c48 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight Special guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight SpecialChar guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight Tag guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight Debug guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight SpecialComment guifg=#7d6a56 guibg=NONE guisp=NONE gui=bold ctermfg=95 ctermbg=NONE cterm=bold
highlight Underlined guifg=#c47a5e guibg=NONE guisp=NONE gui=underline ctermfg=173 ctermbg=NONE cterm=underline
highlight Ignore guifg=#8a6d5e guibg=NONE guisp=NONE gui=NONE ctermfg=95 ctermbg=NONE cterm=NONE
highlight Todo guifg=#d4c88e guibg=#261e19 guisp=NONE gui=bold ctermfg=186 ctermbg=234 cterm=bold
highlight DiffAdd guifg=#bf886f guibg=#261e19 guisp=NONE gui=NONE ctermfg=137 ctermbg=234 cterm=NONE
highlight DiffChange guifg=#cf9c4a guibg=#261e19 guisp=NONE gui=NONE ctermfg=179 ctermbg=234 cterm=NONE
highlight DiffDelete guifg=#c45a5a guibg=#261e19 guisp=NONE gui=NONE ctermfg=167 ctermbg=234 cterm=NONE
highlight DiffText guifg=#d8c1b8 guibg=#453930 guisp=NONE gui=bold ctermfg=181 ctermbg=237 cterm=bold
highlight diffAdded guifg=#bf886f guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight diffRemoved guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight diffChanged guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticSignError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingError guifg=#c45a5a guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextError guifg=#c45a5a guibg=#261e19 guisp=NONE gui=NONE ctermfg=167 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticWarn guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticSignWarn guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingWarn guifg=#cf9c4a guibg=NONE guisp=NONE gui=NONE ctermfg=179 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextWarn guifg=#cf9c4a guibg=#261e19 guisp=NONE gui=NONE ctermfg=179 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#cf9c4a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticInfo guifg=#c47a5e guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticSignInfo guifg=#c47a5e guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingInfo guifg=#c47a5e guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextInfo guifg=#c47a5e guibg=#261e19 guisp=NONE gui=NONE ctermfg=173 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#c47a5e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticHint guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight DiagnosticSignHint guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingHint guifg=#be9b8c guibg=NONE guisp=NONE gui=NONE ctermfg=138 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextHint guifg=#be9b8c guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#be9b8c gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticOk guifg=#bf886f guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticSignOk guifg=#bf886f guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticFloatingOk guifg=#bf886f guibg=NONE guisp=NONE gui=NONE ctermfg=137 ctermbg=NONE cterm=NONE
highlight DiagnosticVirtualTextOk guifg=#bf886f guibg=#261e19 guisp=NONE gui=NONE ctermfg=137 ctermbg=234 cterm=NONE
highlight DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#bf886f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight DiagnosticUnnecessary guifg=#7d6a56 guibg=NONE guisp=NONE gui=italic ctermfg=95 ctermbg=NONE cterm=italic
highlight DiagnosticDeprecated guifg=NONE guibg=NONE guisp=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=NONE
highlight SpellBad guifg=NONE guibg=NONE guisp=#c45a5a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellCap guifg=NONE guibg=NONE guisp=#cf9c4a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellLocal guifg=NONE guibg=NONE guisp=#c47a5e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight SpellRare guifg=NONE guibg=NONE guisp=#9a7abf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
highlight LspReferenceText guifg=NONE guibg=#453930 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspReferenceRead guifg=NONE guibg=#453930 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspReferenceWrite guifg=NONE guibg=#453930 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
highlight LspInlayHint guifg=#aa9287 guibg=#261e19 guisp=NONE gui=NONE ctermfg=138 ctermbg=234 cterm=NONE
highlight LspCodeLens guifg=#aa9287 guibg=NONE guisp=NONE gui=italic ctermfg=138 ctermbg=NONE cterm=italic
highlight LspSignatureActiveParameter guifg=#be9b8c guibg=NONE guisp=NONE gui=bold,underline ctermfg=138 ctermbg=NONE cterm=bold,underline

let g:terminal_ansi_colors = ['#261e19', '#c45a5a', '#b8815a', '#bfa243', '#c76c48', '#9a7abf', '#c47a5e', '#d8c1b8', '#5a4c44', '#d47070', '#c48c6c', '#d4c88e', '#cc8266', '#b49ad4', '#cf9480', '#e8d3ca']
